---

- name: create php repo definition
  apt_repository:
    repo: "ppa:ondrej/php"
    update_cache: true
    state: present

- name: install required php packets
  apt:
    name: "{{ apt_name }}"
    update_cache: true
    state: present
    force_apt_get: true
  loop: "{{ php_packages_list }}"
  loop_control:
    loop_var: apt_name
  notify: restart php
