---
- name: test
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    macs: 
      - "11:22:33:44:55:66"
      - "11.22.33.44.55.66"
      - "11-22-33-44-55-66"
      - "112233445566"
      - "1:2:3:4:1A:2B"
      - "11233445566"
      - "11.2.33.44.55.66"
      - "112.3344.55.66"
      - "112.3344.5566"
      - "1122.3344.5566"
      - "1:2:3::55:66"
      - "1:2:1G:300:2H:66"
    mac_sep: ':'
  tasks:

    - name: normalize mac filter
      debug:
        msg: "{{ mac | mac_normalize(mac_sep) }}"
      loop: "{{ macs }}"
      loop_control:
        loop_var: mac
      ignore_errors: true       
