---

- name: Install mariadb-server and others specific packages
  vars:
    apt_list:
      - 'mariadb-server'
      - 'python3-dev'
      - 'libmysqlclient-dev'
  apt:
    name: "{{ apt_name }}"
    update_cache: true
    state: present
  loop: "{{ apt_list }}"
  loop_control:
    loop_var: apt_name

- name: Ensure mariadb service is started and enabled
  service:
    name: mariadb
    state: started
    enabled: true

- name: block of install MySQL-python module
  block:
    - name: install MySQL-python module from repo
      pip:
        name: 'mysqlclient'

  rescue:
    - name: copy MySQL-python module to remote host
      copy:
        src: files/mysqlclient-2.1.0.tar.gz
        dest: /tmp/mysqlclient-2.1.0.tar.gz
        owner: root
        group: root
        mode: 0644

    - name: install MySQL-python module from file
      pip:
        name: '/tmp/mysqlclient-2.1.0.tar.gz'
  # end block
- name: Create "{{ db_name }}" database
  mysql_db:
    name: "{{ db_name }}"
    state: present

- name: >
    Create database user "{{ db_user }}" with "{{ db_password }}"
    and "{{ db_name }}".*:ALL privelege
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: '{{ db_name }}.*:ALL'
    state: present
  no_log: true

- name: insert firewalld rule for mysql
  ansible.posix.firewalld:
    port: "{{ mysql_port }}/tcp"
    permanent: true
    state: enabled
    immediate: true
