---

- name: install required linux modules
  apt:
    name: "{{ apt_name }}"
    update_cache: true
  loop:
    - 'apt-transport-https'
    - 'lsb-release'
    - 'ca-certificates'
    - 'openssl'
  loop_control:
    loop_var: apt_name

- name: Create necessary folders
  file:
    path: "{{ cert_path }}"
    state: directory
    recurse: true
    owner: root
    group: root
    mode: 0644

- name: Generate an OpenSSL private key with the default values (4096 bits, RSA)
  openssl_privatekey:
    path: "{{ cert_path }}/{{ cert_name }}.pem"
    force: true
    owner: root
    group: root

- name: Generate an OpenSSL Certificate Signing Request
  openssl_csr:
    path: "{{ cert_path }}/{{ cert_name }}.csr"
    privatekey_path: "{{ cert_path }}/{{ cert_name }}.pem"
    common_name: nginx.localhost
    country_name: RU
    organization_name: ansible
    email_address: ansible@domain.local
    force: true
    owner: root
    group: root

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: "{{ cert_path }}/{{ cert_name }}.crt"
    privatekey_path: "{{ cert_path }}/{{ cert_name }}.pem"
    csr_path: "{{ cert_path }}/{{ cert_name }}.csr"
    provider: selfsigned
    owner: root
    group: root
  register: ca_result

- name: set fact ca_changed
  set_fact:
    ca_changed: "{{ ca_result.changed }}"
